name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd portfolio/src
          npm install

      - name: Build project
        run: |
          cd portfolio/src
          npm run build

      - name: Copy to docs
        run: |
          cp -r portfolio/src/dist/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
